name: CI
on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build executableZip
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
    - id: get-tag-version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        version=$(echo ${{github.ref}} | cut -f3 -d/ | sed 's/^v//')
        echo "::set-output name=version::$version"
    - name: Upload release asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/distributions/kmql-bin-${{ steps.get-tag-version.outputs.version }}.zip
        asset_name: kmql-bin-${{ steps.get-tag-version.outputs.version }}.zip
        asset_content_type: application/zip
